### ISSUE TITLE
6-DT_India_P_Präsentation/Doku

### ISSUE THREAD

**Issue by abickel-3** [hka-mmv/dscb230-exercise#29]
Erstellung der Präsentation und einer Live-Demo sowie einer Ausarbeitung.

**Comment by kiya1013** [comment]
https://github.com/hka-mmv/dscb230-exercise/blob/main/p/india/Live_Demo.ipynb

**Comment by kiya1013** [comment]
https://github.com/hka-mmv/dscb230-exercise/blob/main/p/india/P_2021ss_India.V2.docx
